In [1]:
import pandas as pd

In [3]:
data = [5, 10, 15, 20, 25, 30, 35, 40]

series = pd.Series(data)

print(series)

0     5
1    10
2    15
3    20
4    25
5    30
6    35
7    40
dtype: int64

In [126]:
series2 = pd.Series(data, index = ["a", "b", "c", "d", "e", "f", "g"," h"])

series2.head()

a     5
b    10
c    15
d    20
e    25
dtype: int64

In [128]:
data2 = {'a': 5, 'b': 10, 'c': 15, 'd': 20, 'e': 25, 'f': 30, 'g': 35, 'h': 40}
series3 = pd.Series(data2)
series3.head()

a     5
b    10
c    15
d    20
e    25
dtype: int64

In [14]:
print(type(series))
print(type(series2))
print(type(series3))

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>

In [17]:
bio_data = {
    "Name" : ["Oluwatosin", "Deborah", "Modupeoluwa", "Amajuoritse"],
    "Age" : [27, 28, 29, 30],
    "Country" : ["Nairobi", "Ivorycoast", "Malta", "Bahamas"]
}
df = pd.DataFrame(bio_data)
df.head()

          Name  Age     Country
0   Oluwatosin   27     Nairobi
1      Deborah   28  Ivorycoast
2  Modupeoluwa   29       Malta
3  Amajuoritse   30     Bahamas

In [ ]:
my_profile = [
    {"Name": "Alero", "Age": 40, "Country": "Nigeria"},
    {"Name": "Bukola", "Age": 36, "Country": "Ghana"},
    {"Name": "Shola", "Age": 33, "Country": "Cotonou"}
]
df2 = pd.DataFrame(my_profile)
df2

     Name  Age  Country
0   Alero   40  Nigeria
1  Bukola   36    Ghana
2   Shola   33  Cotonou

In [26]:
my_world = [
    ["Tosin", 27, "UK"],
    ["Anu", 30, "Nigeria"],
    ["Morey", 16, "Portonovo"]
]
df3 = pd.DataFrame(my_world, columns=['Name', 'Age', 'Country'])
df3

    Name  Age    Country
0  Tosin   27         UK
1    Anu   30    Nigeria
2  Morey   16  Portonovo

In [27]:
print(type(df))
print(type(df2))
print(type(df3))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>

In [ ]:
food_profile = [
    ["Rice", "Carbohydrates", 1000],
    ["Eggs", "Protein", 1500],
    ["Fruits", "Vitamins", 2000],
    ["Fats", "Oil", 2500]
    ]
df = pd.DataFrame(food_profile, columns=['Food', '  FoodClass', 'Price'])
df.head()

     Food      FoodClass  Price
0    Rice  Carbohydrates   1000
1    Eggs        Protein   1500
2  Fruits       Vitamins   2000
3    Fats            Oil   2500

In [ ]:
food_profile2 = [
    ["Rice", "Carbohydrates", 1000],
    ["Eggs", "Protein", 1500],
    ["Fruits", "Vitamins", 2000],
    ["Fats", "Oil", 2500]
]
df2 = pd.DataFrame(food_profile2, columns=['Food', ' FoodClass', 'Price'], index=["a", "b", "c", "d"])
df2

     Food      FoodClass  Price
a    Rice  Carbohydrates   1000
b    Eggs        Protein   1500
c  Fruits       Vitamins   2000
d    Fats            Oil   2500

In [14]:
def calculate(num1, num2, operation):
    if operation == "add":
        return num1 + num2
    if operation == "subtract":
        return num1 - num2
    if operation == "multiply":
        return num1 * num2
    if operation == "divide":
        if num2 == 0:
           return "Error: Division by zero"
    return num1 / num2

In [15]:
print(calculate(12, 4, "add"))
print(calculate(12, 4, "subtract"))
print(calculate(12, 4, "multiply"))
print(calculate(12, 0, "divide"))

16
8
48
Error: Division by zero

In [4]:
def greet_person(*args, **kwargs):
    if not args and not kwargs:
        print("Hello, Guest! Welcome to Python!")
        return
    for name in args:
        if "title" in kwargs:
            print(f"Hello, {kwargs['title']} {name}! Welcome to Python!")
        else:
            print(f"Hello, {name}! Welcome to python!")

In [5]:
greet_person()

Hello, Guest! Welcome to Python!

In [6]:
greet_person("Oluwatosin", "Deborah", "Modupeoluwa")

Hello, Oluwatosin! Welcome to python!
Hello, Deborah! Welcome to python!
Hello, Modupeoluwa! Welcome to python!

In [7]:
greet_person("Oluwatosin", "Deborah", title = "Dr")

Hello, Dr Oluwatosin! Welcome to Python!
Hello, Dr Deborah! Welcome to Python!